"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { initializeApp, FirebaseApp } from "firebase/app";
import { createContext } from "react";
// import { FirebaseApp, getAuth, onAuthStateChanged } from 'firebase/auth';

const inter = Inter({ subsets: ["latin"] });

// interface FirebaseContextType {
//   app: FirebaseApp;
//   user: any; // You can replace 'any' with a more specific user type if you have one
// }

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyDW7kQixbfr_9P4Iv8p0QU4DYrIHf2y3Iw",
  authDomain: "snug-ca812.firebaseapp.com",
  projectId: "snug-ca812",
  storageBucket: "snug-ca812.appspot.com",
  messagingSenderId: "489534713464",
  appId: "1:489534713464:web:24d3a8f2a50e3e837ac78d",
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
// const user = 2;

const FirebaseContext = createContext(null);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FirebaseContext.Provider value={app}>
          <Navbar />
          <div className="max-w-7xl m-auto px-4">{children}</div>
        </FirebaseContext.Provider>
      </body>
    </html>
  );
}
